# Netlify Configuration File

[build]
  # No build command needed - static site
  publish = "."

[[headers]]
  # Apply these headers to all routes
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  # Cache static assets
  for = "/chart.min.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Custom 404 page (optional)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
